[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
riscv = "0.11.1"
allocator = { path = "../allocator" }
spin = "0.9.8"
bitflags = "1.2.1"
log = "0.4"
xmas-elf = "0.7.0"

[profile.release]
debug = true
