[package]
name = "os"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
riscv = "0.11.1"
buddy_system_allocator = "0.6"
spin = "0.9.8"

[profile.release]
debug = true
