[package]
name = "user"
version = "0.1.0"
edition = "2021"

[dependencies]
allocator = { path = "../allocator" }
sync = { path = "../sync" }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.9.8"

[profile.release]
debug = true